### ISSUE TITLE
Example with NodeJS

### ISSUE THREAD

**Issue by difagume** [pavlov99/watertext#3]
Hello I'm trying to use the library in NodeJS to add watermark to the images I store on the server, you could perhaps add an example of its use, thank you very much

**Comment by pavlov99** [comment]
Hi @difagume 

watertext relies on window.document.canvas which is not available for Node.

Note sure what the solution should be. One possible way is to provide canvas as an argument to watertext and use something like https://github.com/Automattic/node-canvas

**Comment by difagume** [comment]
I think I got a little confused because I saw in the features that watertext works with NodeJS.
I will check node-canvas, thank you very much
